# Write your makefile for Lab 9 to help you efficiently generate the executable program.
# Each time after you modify some code, save the file and run make, you may need to fix some
# errors and run make again. make will help you efficiently rebuild the program every time you
# make a change.


# You may need to add some lines to the Makefile to compile your program.
# You may need to add some lines to the Makefile to link your program.


all:
	gcc -c SortingList.cpp
	g++ term.cpp autocomplete.cpp SortingList.cpp Lab9.cpp -o Lab9

